ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
==	Einführung und Ziele
FitLog wurde in der Blockwoche "WEBLAB" im Frühlingssemester 2026 an der Hochschuel Luzern, Studiengang Computer Sience, umgesetzt. Das Ziel dieses Projektes ist es eine Webanwendung von Grund auf zu entwickeln inklusive deployment. 

=== Persönliche Ziele
- Webapplikation von Grund auf selber schreiben
- Angular Grundlagenwissen erhöhen
- NestJS kennenlernen
- Architekturentscheide treffen und begründen können -> auch mal etwas ausprobieren und damit versuchen zu arbeiten

=== Mean Features FitLog
- Trainings / Workouts manuell tracken (manuelle Eingabe von Einheiten)
- Filterung der Einheiten in einer Listenansicht
- Löschen und Bearbeiten von Einheiten direkt in der Listenansicht
- TBD

=== Projekt Anforderungen aus Aufgabenstellung
Nachfolgend sind die grundlegenden Anforderungen für das Weblab-Projekt aufgeführt.

==== Allgemeines
* Verwendung von AI (Agents) ist erlaubt
* **Sie** (nicht AI) sollten ca. 60h in die Arbeit investieren
* Es ist ein strukturiertes und systematisches Entwicklungsvorgehen anzuwenden.


==== Funktionale Anforderungen
Diese Anforderungen verstehen sich als **Mindestanforderungen**

* Die Applikation muss das Erstellen, Anzeigen, Ändern und Löschen einer selbständig definierten Resource ermöglichen.
* Die Daten müssen persistent in einer Datenbank abgelegt werden.
* Die Daten müssen in mindestens zwei inhaltlich unterschiedlichen Darstellungsformen präsentiert werden.

==== Nicht funktionale Anforderungen
* Die Applikation soll neben der Desktop-Ansicht, auch für die Mobile/Tablet-Ansicht optimiert sein.
* Die Funktionalitäten sollen mittels sinnvollen automatisierten **Unit/Integration/E2E-Tests** überprüft werden.
* Lighthouse-Score: https://developer.chrome.com/docs/lighthouse?hl=de von mindestens 90 (Durchschnitt aller Analysen) für Mobile sowie Desktop.
* Das **Prod-Bundle** der Applikation soll reproduzierbar gestartet werden können.
  * Option 1: Deployed auf einer öffentlichen URL
  * Option 2: via Docker-Compose mit einem Command (`docker compose up`) ausführbar
* Code-Lesbarkeit & Erweiterbarkeit
* Sinnvolle & durchdachte Strukturierung der gesamten Applikation

==== Optionale Ideen
* Automatisiertes Deployment 
* API-First-Ansatz
* Eigene Design Library / Component Library
* Login / Authentifizierung 
* Rollen und Berechtigungen
* ...

=== Stakeholder


[cols="1,1,2" options="header"]
|===
|Rolle |Name |Erwartungshaltung
| Dozent | Dominik Witschard| Projektanforderungen erfüllen, Modul bestehen
| Studentin | Laura Grüter | Webapplikation von Grund auf implementieren, Lernerfolge, Modul bestehen 
|===
