ifndef::imagesdir[:imagesdir: ../images]

[[section-building-block-view]]
== Bausteinsicht
=== Whitebox Gesamtsystem

TBD: Diagramm

_**<Übersichtsdiagramm>**_

Begründung:: Das System ist nach einer 3-Schichten-Architektur (Frontend, Backend, Datenbank) aufgebaut, um Benutzeroberfläche und Datenhaltung zu trennen.

Enthaltene Bausteine:: 
- Web-Client (Single Page Application)
- API-Server (Backend)
- Datenbank (Persistenzschicht)

Wichtige Schnittstellen:: REST-API zwischen Web-Client und API-Server.

==== Web-Client

Zweck:: Ermöglicht User das Erstellen, Löschen, Bearbeiten und Durchsuchen von Workouts
Schnittstelle:: Bietet keine eigenen Services an, konsumiert die REST-API des API-Servers.
Ablageort:: `/src/frontend/` -> TBD

==== API-Server
Zweck:: Verarbeitet Geschäftslogik, validiert Workouts und kommuniziert mit der Datenbank.
Schnittstelle:: REST-Schnittstelle über HTTP/JSON (Port ?) TBD
Ablageort:: `/src/backend/ -> TBD

==== Datenbank
Zweck:: Speichert Workouts persistent
Schnittstelle:: TBD

=== Ebene 2
==== Whitebox _<Baustein 1>_

TBD Diagramm frontend / (backend) zusammenspiel


