= Arbeitsjournal

In diesem File sind die Tätigkeiten zum Projekt dokumentiert.


[cols="1,1,6"]
|===
|**Datum** |**Stunden** | **Tätigkeit**

|31.08.2026 | 1 | 
    Projektidee brainstorming
|01.09.2026 | 2 | 
    Projektauftrag erstellen
|02.09.2026 | 4 | 
    Projekt aufsetzen, Templates erstellen, erste Versuche im Frontend
| 03.09.2026 | 6 | 
    Doku templates, Recherche backend / DB, DB und backend einrichten, CRUD Methode erstellen, Testing, Doku
| 04.09.2026 | 3 | 
    frontend für workouts, UI ausprobieren
| 05.09.2026 | 4 | 
    frontend: Listenansicht, Angular Material recherche, Code Struktur ausprobieren
| 10.09.2026 | 5 | 
    docker config für deployment, cypress setup und erster Test
| 11.09.2026 | 2 | 
    paginator implementiert, an Doku gearbeitet
| 14.09.2026 | 5 | 
    refactor frontend, bug fix dialog box Kalenderpicker, fix Datumsprobleme, implementieren globale Datumsfunktionen, Dokue überarbeiten, Kalenderansicht eingebaut, fix Sortierung
| 15.09.2026 | 2 | 
    system settings for theme, improve styling, some refactoring, documentation
| 16.09.2026 | 4 | 
    create-button, page-header und action-toolbar als shared library und einbauen in bestehende Komponenten, Architekturentscheide ergänzen, improve styling, Kalenderansicht überarbeitet
| 17.09.2026 | 5 | 
    page header in Kalenderansicht, backend für categories, workouts mit categories eräganzen im backend, backend Tests, manuelles swagger testing, Dokumentation
| 18.09.2026 | 2 | 
    start frontend für Kategorien
| 19.09.2026 | 2 | 
    Table in shared component auslagern -> Start und Konzept, ohne commit
| 20.09.2026 | 7 | 
    Tabelle als shared component ausgelagert, shared components refactor, Tests geschrieben, config angepasst, Kategorien frontend, Workouts mit Kategorien erweitert, frontend Unit Tests, Dokumentation
| 21.09.2026 | 5 | 
    code rafactor, error messages im frontend, Einheitlichkeit, bug fixes, Lighthouse Performance verbessern, Dokumentation, e2e Tests
| 24.09.2026 | 4 | 
    Refactoring, Doku
| 25.09.2026 | ? | 
    Abschluss Doku und Abgabe
    

|===

**Total Stunden**: 63
